#!/bin/bash
# Single-node PD auto benchmark driven by launch_and_bench_server_pddisagg.sh.
# Goal: keep the same bench flow as 2nodes_pddisag.sh, but run locally on one machine.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILE_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
LAUNCH_AND_BENCH_SCRIPT="${SCRIPT_DIR}/launch_and_bench_server_pddisagg.sh"
LAUNCH_SERVER_SCRIPT="${SCRIPT_DIR}/launch_server_single_node_2p2d_for_launch_and_bench.sh"
BENCH_SCRIPT="${SCRIPT_DIR}/bench_one_batch_server_profile_metrics_trigger.sh"

for f in "$LAUNCH_AND_BENCH_SCRIPT" "$LAUNCH_SERVER_SCRIPT" "$BENCH_SCRIPT"; do
    if [ ! -f "$f" ]; then
        echo "[ERROR] Required script not found: $f"
        exit 1
    fi
done

# Single-node PD defaults
MODEL_PATH=${MODEL_PATH:-"deepseek-ai/DeepSeek-V3"}
BASE_PORT=${BASE_PORT:-8000}
PREFILL_PORT=${PREFILL_PORT:-30000}
DECODE_PORT=${DECODE_PORT:-30001}
PREFILL_NODES=${PREFILL_NODES:-1}
DECODE_NODES=${DECODE_NODES:-1}
DP=${DP:-2}
EP=${EP:-2}
TP=${TP:-2}
MOE_DENSE_TP=${MOE_DENSE_TP:-1}
MEM_FRACTION_STATIC=${MEM_FRACTION_STATIC:-0.9}
MAX_RUNNING_REQUESTS_DECODE=${MAX_RUNNING_REQUESTS_DECODE:-128}
MEM_CHUNKED_PREFILL_SIZE=${MEM_CHUNKED_PREFILL_SIZE:-16384}
ENABLE_DP_ATTENTION=${ENABLE_DP_ATTENTION:-1}
ENABLE_EPLB=${ENABLE_EPLB:-1}

# Bench defaults (aligned with 2nodes_pddisag.sh style)
PROFILE_TRIGGER_THRESHOLD=${PROFILE_TRIGGER_THRESHOLD:-1.0}
PROFILE_POLLING_INTERVAL=${PROFILE_POLLING_INTERVAL:-0.5}
PROFILE_DELAY_STEPS=${PROFILE_DELAY_STEPS:-0}
PROFILE_LOG_INTERVAL=${PROFILE_LOG_INTERVAL:-5.0}
SEND_INTERVAL=${SEND_INTERVAL:-5}
TOTAL_ROUNDS=${TOTAL_ROUNDS:-2}
WAIT_FOR_PROFILE=${WAIT_FOR_PROFILE:-1}
SKIP_WARMUP=${SKIP_WARMUP:-1}
UPDATE_MAX_RUNNING_REQUESTS=${UPDATE_MAX_RUNNING_REQUESTS:-1}
MAX_RUNNING_REQS_UPDATE_RETRIES=${MAX_RUNNING_REQS_UPDATE_RETRIES:-30}
TARGET_DP_RANK=${TARGET_DP_RANK:-0}
BS=${BS:-256}
IL=${IL:-1000}
OL=${OL:-100}
PROFILE_STEPS=${PROFILE_STEPS:-50}

# launch_and_bench compatibility switches for single-node mode
SKIP_INTERNAL_ROUTER=${SKIP_INTERNAL_ROUTER:-1}
EXIT_WITH_ERROR_TO_STOP_JOB=${EXIT_WITH_ERROR_TO_STOP_JOB:-0}
ENABLE_PD_DISAGG=${ENABLE_PD_DISAGG:-1}
ENABLE_DEEPGEMM=${ENABLE_DEEPGEMM:-0}
PREFILL_URL=${PREFILL_URL:-"http://127.0.0.1:${PREFILL_PORT}"}
DECODE_URL=${DECODE_URL:-"http://127.0.0.1:${DECODE_PORT}"}

echo "=========================================="
echo "Single-node PD auto benchmark (launch_and_bench)"
echo "=========================================="
echo "Model: $MODEL_PATH"
echo "Launch-and-bench: $LAUNCH_AND_BENCH_SCRIPT"
echo "Launch server: $LAUNCH_SERVER_SCRIPT"
echo "Bench script: $BENCH_SCRIPT"
echo "DP/EP/TP: $DP/$EP/$TP"
echo "BS/IL/OL: $BS/$IL/$OL"
echo "Router URL: http://127.0.0.1:$BASE_PORT"
echo "Prefill URL: $PREFILL_URL"
echo "Decode URL: $DECODE_URL"
echo "=========================================="

(
    cd "$PROFILE_DIR"
    if [ -n "${RESULT_DIR:-}" ]; then
        export RESULT_DIR
    fi
    MODEL_PATH="$MODEL_PATH" \
    SERVER_READY_URL="http://127.0.0.1:${BASE_PORT}" \
    BASE_PORT="$BASE_PORT" \
    ROUTER_PORT="$BASE_PORT" \
    PREFILL_PORT="$PREFILL_PORT" \
    DECODE_PORT="$DECODE_PORT" \
    PREFILL_NODES="$PREFILL_NODES" \
    DECODE_NODES="$DECODE_NODES" \
    DP="$DP" EP="$EP" TP="$TP" MOE_DENSE_TP="$MOE_DENSE_TP" \
    MEM_FRACTION_STATIC="$MEM_FRACTION_STATIC" \
    MAX_RUNNING_REQUESTS_DECODE="$MAX_RUNNING_REQUESTS_DECODE" \
    MEM_CHUNKED_PREFILL_SIZE="$MEM_CHUNKED_PREFILL_SIZE" \
    CHUNKED_PREFILL_SIZE="$MEM_CHUNKED_PREFILL_SIZE" \
    ENABLE_DP_ATTENTION="$ENABLE_DP_ATTENTION" \
    ENABLE_EPLB="$ENABLE_EPLB" \
    PROFILE_TRIGGER_THRESHOLD="$PROFILE_TRIGGER_THRESHOLD" \
    PROFILE_POLLING_INTERVAL="$PROFILE_POLLING_INTERVAL" \
    PROFILE_DELAY_STEPS="$PROFILE_DELAY_STEPS" \
    PROFILE_LOG_INTERVAL="$PROFILE_LOG_INTERVAL" \
    SEND_INTERVAL="$SEND_INTERVAL" \
    TOTAL_ROUNDS="$TOTAL_ROUNDS" \
    WAIT_FOR_PROFILE="$WAIT_FOR_PROFILE" \
    SKIP_WARMUP="$SKIP_WARMUP" \
    UPDATE_MAX_RUNNING_REQUESTS="$UPDATE_MAX_RUNNING_REQUESTS" \
    UPDATE_MAX_RUNNING_REQS="$UPDATE_MAX_RUNNING_REQUESTS" \
    MAX_RUNNING_REQS_UPDATE_RETRIES="$MAX_RUNNING_REQS_UPDATE_RETRIES" \
    TARGET_DP_RANK="$TARGET_DP_RANK" \
    BS="$BS" IL="$IL" OL="$OL" PROFILE_STEPS="$PROFILE_STEPS" \
    PREFILL_URL="$PREFILL_URL" \
    DECODE_URL="$DECODE_URL" \
    ENABLE_PD_DISAGG="$ENABLE_PD_DISAGG" \
    ENABLE_DEEPGEMM="$ENABLE_DEEPGEMM" \
    SKIP_INTERNAL_ROUTER="$SKIP_INTERNAL_ROUTER" \
    EXIT_WITH_ERROR_TO_STOP_JOB="$EXIT_WITH_ERROR_TO_STOP_JOB" \
    bash "$LAUNCH_AND_BENCH_SCRIPT" "$LAUNCH_SERVER_SCRIPT" "$BENCH_SCRIPT"
)
